routes/web.php
<?php

use App\Http\Controllers\EventCategoriesController;
use App\Http\Controllers\EventsController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('backend.layouts.master');
    });
    Route::get('home', function () {
        return view('backend.layouts.master');
    });
    Route::resource('events', EventsController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('categorie', EventCategoriesController::class);
});

app/Models/Events.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Events extends Model
{
    use Sluggable;
    use HasFactory;
    protected $table = "events";

    protected $fillable = [
    	"event_title",
        "event_slug",
        "event_status",
        "event_image",
        "event_description",
        "category_id",
    ];

    public function sluggable(): array
    {
        return [
            'event_slug' => [
                'source' => 'event_title'
            ]
        ];
    }
    public function tags()
    {
        return $this->belongsToMany(Tags::class);
    }




}

app/Http/Controllers/EventsController.php
<?php

namespace App\Http\Controllers;

use App\Models\EventCategories;
use App\Models\Events;
use App\Models\EventTag;
use App\Models\Tags;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\File;
use Yajra\DataTables\Facades\DataTables;

class EventsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->uploadpath = public_path("/images/events");
        if (!File::exists($this->uploadpath)) {
            File::makeDirectory($this->uploadpath, 0777, true, true);
        }
}
    public function index(Request $request)
    {

        if($request->ajax()){
            $data = Events::select('*');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row) {
                    $actionBtn = '
                <a class="btn btn-sm btn-success edit-item-btn"
                    href="' . route('events.edit', $row->id) . '">Edit</a>
                    <button type="submit" id="'.$row->id.'"
                        class="btn btn-sm btn-danger remove-item-btn delete"
                        data-toggle="tooltip" title="Delete">Delete</button>
                ';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('backend.events.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories =EventCategories::all();
        $tags = Tags::all();
        return view('backend.events.create',compact('categories','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "event_title" => "required|unique:events,event_title",
            "event_status"=>"required",
            "event_image"=>'image|mimes:png,jpg,jpeg,gif',
            "event_description"=>"required",
            "category_id"=>"required",
        ]);
         try {
            $events =  new Events();
            $events->event_title=$request->input('event_title');
            $events->event_status=$request->input('event_status');

            if ($request->hasfile('event_image')) {
                $pages_image = $request->file('event_image');
                $filename = time() . "." . $pages_image->getClientOriginalExtension();
                $pages_image->move($this->uploadpath, $filename);
                $events->event_image=$filename;
            }
            $events->event_description=$request->input('event_description');
            $events->category_id=$request->input('category_id');
            $events->save();
                    if (!empty($request["tags"])) {
                foreach ($request["tags"] as $t) {
                    $tag = new EventTag();
                    $tag->event_id = $events->id;
                    $tag->tag_id = $t;
                    $tag->save();
                }
            }
            request()->session()->flash("successMessage", "Events added successfully");
        }
        catch (\Exception $e) {
            request()->session()->flash('unsuccessMessage', 'Failed to add Events');
        }
        return redirect(route('events.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function show(Events $events)
    {



    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $events = Events::find($id);
        $event_tag = EventTag::where("event_id", $id)->get('tag_id');
        $edit_tags = [];
        foreach($event_tag as $item){
            $edit_tags[] = $item->tag_id;
        }
        // dd($edit_tags);
        $tags = Tags::all();
        $categories =EventCategories::all();
        return view('backend.events.edit',compact('events','edit_tags','tags','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {


        $request->validate([
            "event_title" => "required|unique:events,event_title,".$id,
            "event_status"=>"required",
            "event_image"=>'image|mimes:png,jpg,jpeg,gif',
            "event_description"=>"required",
            "category_id"=>"required",
        ]);
         try {
            $events = Events::where("id", $id)->first();
            $events->event_title=$request->input('event_title');
            $events->event_status=$request->input('event_status');

            if ($request->hasfile('event_image')) {
                $image = $events->event_image;
                $pages_image = $request->file('event_image');
                $filename = time() . "." . $pages_image->getClientOriginalExtension();
                $pages_image->move($this->uploadpath, $filename);
                $events->event_image=$filename;
                File::delete($this->uploadpath . '/' . $image);
            }
            else{
                $events->event_image = $events['event_image'];
            }
            $events->event_description=$request->input('event_description');
            $events->category_id=$request->input('category_id');
            $events->save();
            EventTag::where("event_id", $events->id)->delete();
                    if (!empty($request["tags"])) {
                foreach ($request["tags"] as $t) {
                    $tag = new EventTag();
                    $tag->event_id = $events->id;
                    $tag->tag_id = $t;
                    $tag->save();
                }
            }
            request()->session()->flash("successMessage", "Events update successfully");
        }
        catch (\Exception $e) {
            request()->session()->flash('unsuccessMessage', 'Failed to update Events');
        }
        return redirect(route('events.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Events  $events
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            EventTag::where("event_id", $id)->delete();
            Events::destroy($id);
        }
        catch(\Exception $e){
            return response()->json(["status" => "Event deleted Fail"]);
        }
        return response()->json(["status" => "Event deleted successfully"]);

    }
}

resources/views/backend/events/create.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | Add Events')
@section('content-header')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Event</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('events.index') }}">Events</a></li>
                        <li class="breadcrumb-item active">Add Event</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <form action="{{ route('events.store') }}" method="POST" id="news_store" enctype="multipart/form-data" autocomplete="off">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Event</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="event_title">Title</label>
                                    <input type="text" class="form-control" name="event_title" id="title"
                                        placeholder="Title" value="{{ old('event_title') }}">
                                        @if ($errors->has('event_title'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('event_title') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Events Image</label>
                                    <img class="card-img-top" src="{{ asset('default.jpg') }}" alt="" height="200px"
                                        width="200px" id="pic">

                                </div>
                            </div>
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <input type="file" name="event_image"
                                        onchange="pic.src=window.URL.createObjectURL(this.files[0])" accept="image/*">
                                    </p>
                                </div>
                                @if ($errors->has('event_image'))
                                <span class="help-block" style="color: #f86c6b;">
                                    {{ $errors->first('event_image') }}
                                </span>
                            @endif
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Status</label><br>
                                    <div class="row">
                                        <div class="col-md-12" style="margin-bottom: 5px;">
                                            <input type="radio" name="event_status" value="1"
                                                {{ !is_null(old('event_status')) ? (old('event_status') == 1 ? 'checked' : '') : '' }}>
                                            <span>Publish</span>
                                        </div>
                                        <div class="col-md-12">
                                            <input type="radio" name="event_status" value="0"
                                                {{ !is_null(old('event_status')) ? (old('event_status') == 0 ? 'checked' : '') : '' }}>
                                            <span>Unpublish</span><br>
                                        </div>
                                    </div>
                                    @if ($errors->has('event_status'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('event_status') }}
                                        </span>
                                    @endif
                                </div>
                            </div>



                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label>Tags</label>
                                    <div class="row d-flex justify-content-left">
                                        <div class="col-md-6"> <select id="choices-multiple-remove-button"
                                                name="tags[]" placeholder="Select upto 5 tags" multiple>
                                                @foreach ($tags as $items)
                                                    <option value="{{ $items->id }}"
                                                        {{ !empty(old('items_id')) ? (in_array($items->id, old('items_id')) ? 'selected' : '') : '' }}>
                                                        {{ $items->tags_title }}</option>
                                                @endforeach
                                            </select>
                                            @if ($errors->has('tags.*'))
                                                <span class="help-block" style="color: #f86c6b;">
                                                    {{ $errors->first('tags.*') }}
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <!-- /.form-group -->
                            </div>
                            <div class="col-md-6 mb-10">
                                <div class="form-group">
                            <label for="category_id">Choose a Categories</label>

                            <select name="category_id" class="form-control" id="cars">
                                @foreach ($categories as $items)
                                <option value="{{ $items->id }}"
                                    {{ !empty(old('items_id')) ? (in_array($items->id, old('items_id')) ? 'selected' : '') : '' }}>
                                    {{ $items->event_categorie_title }}</option>
                            @endforeach
                            </select>
                            @if ($errors->has('tags.*'))
                            <span class="help-block" style="color: #f86c6b;">
                                {{ $errors->first('tags.*') }}
                            </span>
                        @endif
                                </div>
                            </div>







                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="event_description">Description</label>
                                    <textarea type="text" class="form-control editor" name="event_description" id="description">{{ old('event_description') }}</textarea>
                                </div>
                            </div>


                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="col-12" style="margin-bottom: 10px;">
                            <input type="submit" value="Submit" class="btn btn-sm btn-primary float-right">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/events/edit.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | Edit Events')
@section('content-header')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Events</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('events.index') }}">Events</a></li>
                        <li class="breadcrumb-item active">Edit</li>

                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection
@section('content')

{{--  {{  dd($events) }}  --}}
    <form class="form-horizontal" method="post" action="{{ route('events.update', $events->id) }}"
        id="news_edit"enctype="multipart/form-data" autocomplete="off">
        @csrf
        @method('patch')
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Events</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="event_title">Title</label>
                                    <input type="text" class="form-control" name="event_title" id="title"
                                        placeholder="Title"  value="{{ !empty($events) ? $events->event_title : '' }}">
                                        @if ($errors->has('event_title'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('event_title') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Events Image</label>
                                    <img class="card-img-top" src="{{ (($events->event_image != '') && file_exists(public_path('images/events/'.$events->event_image))) ? asset('images/events/'.$events->event_image) : asset('default.jpg') }}"  alt="" height="200px"
                                        width="200px" id="pic">

                                </div>
                            </div>
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <input type="file" name="event_image"
                                        onchange="pic.src=window.URL.createObjectURL(this.files[0])" accept="image/*">
                                    </p>
                                </div>
                                @if ($errors->has('event_image'))
                                <span class="help-block" style="color: #f86c6b;">
                                    {{ $errors->first('event_image') }}
                                </span>
                            @endif
                            </div>
                            <div class="form-group">
                                <label>Status</label><br>
                                <div class="row">
                                    <div class="col-md-12" style="margin-bottom: 5px;">
                                        <input type="radio" name="event_status" value="1"
                                <input type="radio" name="status" value="1" {{ !is_null($events) ? (($events->event_status==1)? 'checked' : '') : '' }}>
                                        <span>Active</span>
                                    </div>
                                    <div class="col-md-12">
                                        <input type="radio" name="event_status" value="0"
                                        {{ !is_null($events) ? (($events->event_status==0)? 'checked' : '') : '' }}>
                                        <span>Inactive</span><br>
                                    </div>
                                </div>
                                @if ($errors->has('event_status'))
                                    <span class="help-block" style="color: #f86c6b;">
                                        {{ $errors->first('event_status') }}
                                    </span>
                                @endif
                            </div>
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label>Tags</label>
                                    <div class="row d-flex justify-content-left">
                                        <div class="col-md-6"> <select id="choices-multiple-remove-button"
                                                name="tags[]" placeholder="Select upto 5 tags" multiple>
                                                @foreach ($tags as $items)
                                                    <option value="{{ $items->id }}"
                                                        {{ !empty($events)? (in_array($items->id, $edit_tags)? 'selected' : '') : '' }}>{{ $items->tags_title}}</option>
                                                        {{ $items->tags_title }}</option>
                                                @endforeach
                                            </select>
                                            @if ($errors->has('tags.*'))
                                                <span class="help-block" style="color: #f86c6b;">
                                                    {{ $errors->first('tags.*') }}
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <!-- /.form-group -->
                            </div>
                            <div class="col-md-6 mb-10">
                                <div class="form-group">
                            <label for="category_id">Choose a Categories</label>

                            <select name="category_id" class="form-control">
                                @foreach ($categories as $items)
                                <option value="{{ $items->id }}"
                                   @if($items->id == $events->category_id)  selected @endif >
                                    {{ $items->event_categorie_title }}</option>
                            @endforeach
                            </select>
                            @if ($errors->has('tags.*'))
                            <span class="help-block" style="color: #f86c6b;">
                                {{ $errors->first('tags.*') }}
                            </span>
                        @endif
                                </div>
                            </div>
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="event_description">Description</label>
                                    <textarea type="text" class="form-control editor" name="event_description" id="description">{{ ($events->event_description) }}</textarea>
                                </div>
                            </div>


                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="col-12" style="margin-bottom: 10px;">
                            <input type="submit" value="Update" class="btn btn-sm btn-primary float-right">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/events/index.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | List Events')
@section('content-header')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            Events
                        </li>
                        <li class="breadcrumb-item active">
                            List
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title"><strong>List Events</strong></h3>
                    <div class="card-tools" style="display: flex;">
                        <div style="margin-right: 10px;">
                            <a href="{{ route('events.create') }}" class="btn btn-success btn-xs" title="Add Events">Add
                                Events</a>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="card-body table-responsive no-padding">
                    <table class="table table-hover" id="myTableEvents">
                        <div my-2>
                            @if (session('successMessage'))
                                <div class="alert alert-success"  id="message_id" role="alert">
                                    {{ session('successMessage') }}
                                </div>
                                @elseif (session('unsuccessMessage'))
                                <div class="alert alert-danger"  id="message_id" role="alert">
                                    {{ session('unsuccessMessage') }}
                                </div>
                            @endif
                        </div>
                        <thead>

                            <tr>

                                <th width="5%">S.N</th>
                                <th width="33%">Title</th>
                                <th width="8%">Status</th>
                                <th width="8%">Category</th>
                                <th width="15%">Action</th>

                            </tr>

                        </thead>

                    </table>

                </div>

            </div>

            <!-- /.box -->

        </div>

    </div>

@endsection
@section('after-script')

<script type="text/javascript">
    $(function () {

      var table = $('#myTableEvents').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('events.index') }}",
          columns: [
              {data: 'id', name: 'id'},
              {data: 'event_title', name: 'event_title'},
              {data: 'event_status', name: 'event_status'},
              {data: 'category_id', name: 'category_id'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });
      $("body").on('click', '.delete', function (e){
        e.preventDefault();
        var deleteId = $(this).attr("id");
        var url = '{{ url('/') }}' +'/events/'+ deleteId;
        swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this Events!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((willDelete) => {
          if (willDelete) {
            $.ajax({
                headers:{'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
              type: "delete",
              url: url,
              success: function (response){
                swal(response.status, {
                  icon: "success",
                }).then((result) => {
                  location.reload();
                });
              },
            });
          } else {
            swal("Your Tags is safe!");
          }
        });
      });

    });
  </script>
@endsection