routes/web.php
<?php

use App\Http\Controllers\EventCategoriesController;
use App\Http\Controllers\EventsController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('backend.layouts.master');
    });
    Route::get('home', function () {
        return view('backend.layouts.master');
    });
    Route::resource('events', EventsController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('categorie', EventCategoriesController::class);
});

app/Http/Controllers/EventCategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\EventCategories;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\File;

class EventCategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {

        if($request->ajax()){
            $data =EventCategories::select('*');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row) {
                    $actionBtn = '
                <a class="btn btn-sm btn-success edit-item-btn"
                    href="' . route('categorie.edit', $row->id) . '">Edit</a>
                    <button type="submit" id="'. $row->id.'"
                        class="btn btn-sm btn-danger remove-item-btn delete"
                        data-toggle="tooltip" title="Delete">Delete</button>
                ';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('backend.event_categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.event_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "event_categorie_title" => "required|unique:event_categories,event_categorie_title",
            "event_categorie_status" => "required",
        ]);
        try {
            $input = $request->all();
            // dd($input);
            EventCategories::create($input);
            request()->session()->flash("successMessage", "Categories added successfully");
        }
        catch (\Exception $e) {
            request()->session()->flash('unsuccessMessage', 'Failed to add Categories');
        }
        return redirect(route('categorie.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\EventCategories  $eventCategories
     * @return \Illuminate\Http\Response
     */
    public function show(EventCategories $eventCategories)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\EventCategories  $eventCategories
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $categories =EventCategories::find($id);
        return view('backend.event_categories.edit',compact('categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\EventCategories  $eventCategories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $request->validate([
            "event_categorie_title" => "required|unique:tags,tags_title,".$id,
            "event_categorie_status" => "required",
        ]);
        try{
            $categories = EventCategories::find($id);
            $categories->event_categorie_title = $request->input('event_categorie_title');
            $categories->event_categorie_status = $request->input('event_categorie_status');
            $categories->Update();
            request()->session()->flash("successMessage", "Tags Update successfully");


        }
        catch(\Exception $e){
            request()->session()->flash('unsuccessMessage', 'Failed to update Tags');

        }
        return redirect(route('categorie.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\EventCategories  $eventCategories
     * @return \Illuminate\Http\Response
     */
    public function destroy($eventCategories)
    {
        try{
            EventCategories::deleted($eventCategories);
            request()->session()->flash("successMessage", "Tags Delete successfully");
        }
        catch(\Exception $e){
            request()->session()->flash('unsuccessMessage', 'Failed to delete Tags');
        }
        return redirect(route('categorie.index'));
    }
}

resources/views/backend/event_categories/create.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | Add Categories')
@section('content-header')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('categorie.index') }}">Categories</a></li>
                        <li class="breadcrumb-item active">Add Categories</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <form action="{{ route('categorie.store') }}" method="POST" id="news_store" enctype="multipart/form-data" autocomplete="off">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Categories</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="event_categorie_title">Title</label>
                                    <input type="text" class="form-control" name="event_categorie_title" id="event_categorie_title"
                                        placeholder="Title" value="{{ old('event_categorie_title') }}">
                                        @if ($errors->has('event_categorie_title'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('event_categorie_title') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Status</label><br>
                                    <div class="row">
                                        <div class="col-md-12" style="margin-bottom: 5px;">
                                            <input type="radio" name="event_categorie_status" value="1"
                                                {{ !is_null(old('event_categorie_status')) ? (old('event_categorie_status') == 1 ? 'checked' : '') : '' }}>
                                            <span>Active</span>
                                        </div>
                                        <div class="col-md-12">
                                            <input type="radio" name="event_categorie_status" value="0"
                                                {{ !is_null(old('event_categorie_status')) ? (old('event_categorie_status') == 0 ? 'checked' : '') : '' }}>
                                            <span>Inactive</span><br>
                                        </div>
                                    </div>
                                    @if ($errors->has('event_categorie_status'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('event_categorie_status') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="col-12" style="margin-bottom: 10px;">
                           <input type="submit" value="Submit" class="btn btn-sm btn-primary float-right">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/event_categories/edit.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | Edit Categories')
@section('content-header')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('categorie.index') }}">Categories</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <form class="form-horizontal" method="post" action="{{ route('categorie.update',$categories->id)}}"
        id="news_edit" enctype="multipart/form-data" autocomplete="off">
        @csrf
        @method('patch')
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Categorie</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="event_categorie_title">Title</label>
                                    <input type="text" class="form-control" name="event_categorie_title" id="event_categorie_title"
                                        placeholder="Title" value="{{ !empty($categories) ? $categories->event_categorie_title : '' }}">
                                        @if ($errors->has('event_categorie_title'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('event_categorie_title') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Status</label><br>
                                    <div class="row">
                                        <div class="col-md-12" style="margin-bottom: 5px;">
                                            <input type="radio" name="event_categorie_status" value="1"
                                    <input type="radio" name="status" value="1" {{ !is_null($categories) ? (($categories->event_categorie_status==1)? 'checked' : '') : '' }}>
                                            <span>Active</span>
                                        </div>
                                        <div class="col-md-12">
                                            <input type="radio" name="event_categorie_status" value="0"
                                            {{ !is_null($categories) ? (($categories->event_categorie_status==0)? 'checked' : '') : '' }}>
                                            <span>Inactive</span><br>
                                        </div>
                                    </div>
                                    @if ($errors->has('event_categorie_status'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('event_categorie_status') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="col-12" style="margin-bottom: 10px;">
                            <input type="submit" value="Update" class="btn btn-sm btn-primary float-right">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection
@section('after-script')
@endsection

resources/views/backend/event_categories/index.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | List Categories')
@section('content-header')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            Tags
                        </li>
                        <li class="breadcrumb-item active">
                            List
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title"><strong>List Categories</strong></h3>
                    <div class="card-tools" style="display: flex;">
                        <div style="margin-right: 10px;">
                            <a href="{{ route('categorie.create') }}" class="btn btn-success btn-xs" title="Add Tags">Add
                                Categories</a>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="card-body table-responsive no-padding">
                    <div my-2>
                        @if (session('successMessage'))
                            <div class="alert alert-success"  id="message_id" role="alert">
                                {{ session('successMessage') }}
                            </div>
                            @elseif (session('unsuccessMessage'))
                            <div class="alert alert-danger"  id="message_id" role="alert">
                                {{ session('unsuccessMessage') }}
                            </div>
                        @endif
                    </div>
                    <table class="table table-hover" id="myTableCategory">

                        <thead>

                            <tr>
                                <th width="5%">S.N</th>

                                <th width="33%">Title</th>

                                <th width="8%">Status</th>

                                <th width="15%">Action</th>

                            </tr>

                        </thead>

                    </table>

                </div>

            </div>

            <!-- /.box -->

        </div>

    </div>

@endsection
@section('after-script')

<script type="text/javascript">
    $(function () {

      var table = $('#myTableCategory').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('categorie.index') }}",
          columns: [
              {data: 'id', name: 'id'},
              {data: 'event_categorie_title', name: 'event_categorie_title'},
              {data: 'event_categorie_status', name: 'event_categorie_status'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

        $("body").on('click', '.delete', function (e){
          e.preventDefault();
          var deleteId = $(this).data("id");
          var url = '{{ url('/') }}';
          swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this category!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
          }).then((willDelete) => {
            if (willDelete) {
              $.ajax({
                type: "delete",
                url: url +'/admin/category/'+ deleteId,
                data: data,
                success: function (response){
                  swal(response.status, {
                    icon: "success",
                  }).then((result) => {
                    location.reload();
                  });
                },
              });
            } else {
              swal("Your category is safe!");
            }
          });
        });








    });
  </script>
@endsection