routes/web.php
<?php

use App\Http\Controllers\EventCategoriesController;
use App\Http\Controllers\EventsController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('backend.layouts.master');
    });
    Route::get('home', function () {
        return view('backend.layouts.master');
    });
    Route::resource('events', EventsController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('categorie', EventCategoriesController::class);
});

resources/views/backend/includes/content-header.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard </li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

resources/views/backend/includes/control-sidebar.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/backend/includes/footer.blade.php
<footer class="main-footer">

  <strong>Copyright &copy; {{ date('Y') }}</strong>

  All rights reserved.

  <div class="float-right d-none d-sm-inline-block">

    <!-- <b>Version</b> 3.0.5 -->

  </div>

</footer>

resources/views/backend/includes/head.blade.php
<link rel="icon" href="{{ asset('frontend/images/logo.png') }}" type="image/gif" sizes="32*32">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
{{--  <meta name="_token" content="{{ csrf_token() }}">  --}}
<meta name="csrf-token" content="{{ csrf_token() }}" />
<title>@yield('title')</title>
<link rel="icon" href="{{ asset('frontend/images/default-big-image.png') }}">
<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('backend/layout/plugins/fontawesome-free/css/all.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bbootstrap 4 -->

<link rel="stylesheet" href="{{ asset('backend/layout/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">

<!-- iCheck -->

<link rel="stylesheet" href="{{ asset('backend/layout/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">

<!-- JQVMap -->

<link rel="stylesheet" href="{{ asset('backend/layout/plugins/jqvmap/jqvmap.min.css') }}">

<!-- Theme style -->

<link rel="stylesheet" href="{{ asset('backend/layout/dist/css/adminlte.min.css') }}">

<!-- overlayScrollbars -->

<link rel="stylesheet" href="{{ asset('backend/layout/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">

<!-- Daterange picker -->

<link rel="stylesheet" href="{{ asset('backend/layout/plugins/daterangepicker/daterangepicker.css') }}">

<!-- summernote -->

<link rel="stylesheet" href="{{ asset('backend/layout/plugins/summernote/summernote-bs4.css') }}">

<!-- Google Font: Source Sans Pro -->

<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
{{--  <link rel="stylesheet" href="{{ asset('backend/dataTable/jquery.dataTables.min.css')}}">  --}}

<link rel="stylesheet" href="{{ asset('backend/select2/css/select2.min.css')}}">
{{--  <link rel="stylesheet" href="{{ asset('backend/select2-bootstrap4-theme/css/select2-bootstrap4.min.css') }}">  --}}

<link rel="stylesheet" href="{{ asset('backend/layout/plugins/jquery-ui/jquery-ui.theme.min.css') }}">
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">

<link rel="stylesheet" href="{{ asset('backend/custom.css') }}">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
<style>
    .mt-100{margin-top: 100px}
    body{background: #00B4DB;
        background: -webkit-linear-gradient(to right, #0083B0, #00B4DB);
        background: linear-gradient(to right, #0083B0, #00B4DB);
        color: #514B64;
        min-height: 100vh}
</style>

resources/views/backend/includes/nav-bar.blade.php
<!-- Navbar -->

<nav class="main-header navbar navbar-expand navbar-white navbar-light">

  <!-- Left navbar links -->

  <ul class="navbar-nav">

    <li class="nav-item">

      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>

    </li>

    <li class="nav-item d-none d-sm-inline-block">

      <a href="{{ url('/admin/dashboard') }}" class="nav-link">Home</a>
    </li>

  </ul>
</nav>

<!-- /.navbar -->

resources/views/backend/includes/paginator.blade.php
@if ($paginator->hasPages())
    <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
            {{-- Previous Page Link --}}
            @if ($paginator->onFirstPage())
                <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.previous')">
                    <span class="page-link" aria-hidden="true">&laquo;</span>
                </li>
            @else
                <li class="page-item">
                    <a href="{{ $paginator->previousPageUrl() }}" class="page-link" rel="prev" aria-label="@lang('pagination.previous')">&laquo;</a>
                </li>
            @endif

            {{-- Pagination Elements --}}
            @foreach ($elements as $element)
                {{-- "Three Dots" Separator --}}
                @if (is_string($element))
                    <li class="page-item disabled" aria-disabled="true"><span class="page-link">{{ $element }}</span></li>
                @endif

                {{-- Array Of Links --}}
                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        @if ($page == $paginator->currentPage())
                            <li class="active page-item" aria-current="page"><span class="page-link">{{ $page }}</span></li>
                        @else
                            <li class="page-item"><a href="{{ $url }}" class="page-link">{{ $page }}</a></li>
                        @endif
                    @endforeach
                @endif
            @endforeach

            {{-- Next Page Link --}}
            @if ($paginator->hasMorePages())
                <li class="page-item">
                    <a href="{{ $paginator->nextPageUrl() }}" class="page-link" rel="next" aria-label="@lang('pagination.next')">&raquo;</a>
                </li>
            @else
                <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.next')">
                    <span class="page-link" aria-hidden="true">&raquo;</span>
                </li>
            @endif
        </ul>
    </div>
@endif

resources/views/backend/includes/script.blade.php
<!-- jQuery -->
<script src="{{ asset('backend/layout/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('backend/layout/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<!-- Bootstrap 4 -->
<script src="{{ asset('backend/layout/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('backend/layout/plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('backend/layout/plugins/sparklines/sparkline.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('backend/layout/plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('backend/layout/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('backend/layout/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('backend/layout/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}">
</script>
<!-- Summernote -->
<script src="{{ asset('backend/layout/plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('backend/layout/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/layout/dist/js/adminlte.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('backend/layout/dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('backend/layout/dist/js/demo.js') }}"></script>
<script src="{{ asset('backend/ckeditor/ckeditor.js') }}" type="text/javascript"></script>
{{--  <script src="{{ asset('backend/select2/js/select2.full.min.js') }}" type="text/javascript"></script>  --}}
<script src="{{ asset('backend/sweetalert/sweetalert.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('backend/dataTable/jquery.dataTables.min.js') }}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>
<script>
    CKEDITOR.replace("description");
    $(document).ready(function(){

        var multipleCancelButton = new Choices('#choices-multiple-remove-button', {
           removeItemButton: true,
           maxItemCount:5,
           searchResultLimit:5,
           renderChoiceLimit:5
         });


    });
</script>

resources/views/backend/includes/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
   {{--  <a href="{{ route('frontend.home') }}" class="brand-link" target="_blank">  --}}
      <span class="text-uppercase text-primary "  style="width:8rem;">{{ env('APP_NAME') }}</span>
   {{--  </a>  --}}
   <div class="sidebar">
      <nav class="mt-2">
         <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

            <li class="nav-item">
               <a href="{{ route('events.index') }}" class="nav-link">
                  <i class="nav-icon fas fa-ad nav-icon"></i>
                  <p>
                     Events

                  </p>
               </a>
            </li>
            <li class="nav-item ">
                <a href="{{ route('tags.index') }}" class="nav-link">
                   <i class="nav-icon fas fa-ad nav-icon"></i>
                   <p>
                      Tags

                   </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('categorie.index') }}" class="nav-link">
                   <i class="nav-icon fas fa-ad nav-icon"></i>
                   <p>
                      Categorys
                   </p>
                </a>
            </li>


            <li class="nav-item">
                <a href="{{ route('logout') }}" class="nav-link"  onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
   {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </li>
         </ul>
      </nav>
      <!-- /.sidebar-menu -->
   </div>
   <!-- /.sidebar -->
</aside>