routes/web.php
<?php

use App\Http\Controllers\EventCategoriesController;
use App\Http\Controllers\EventsController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('backend.layouts.master');
    });
    Route::get('home', function () {
        return view('backend.layouts.master');
    });
    Route::resource('events', EventsController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('categorie', EventCategoriesController::class);
});

app/Models/Tags.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tags extends Model
{
    use HasFactory;
    protected $table = "tags";

    protected $fillable = [
    	"tags_title",
        "tags_status"
    ];
    public function events()
    {
        return $this->belongsToMany(Events::class);
    }





}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tags;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            $data = Tags::select('*');
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row) {
                    $actionBtn = '
                <a class="btn btn-sm btn-success edit-item-btn"
                    href="' . route('tags.edit', $row->id) . '">Edit</a>
                    <button type="submit" id="'. $row->id.'"
                        class="btn btn-sm btn-danger remove-item-btn delete"
                        data-toggle="tooltip" title="Delete">Delete</button>
                ';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('backend.tags.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "tags_title" => "required|unique:tags,tags_title",
            "tags_status" => "required",
        ]);
        try {
            $input = $request->all();
            Tags::create($input);
            request()->session()->flash("successMessage", "Tags added successfully");
        }
        catch (\Exception $e) {
            request()->session()->flash('unsuccessMessage', 'Failed to add Tags');
        }
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function show(Tags $tags)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tags = Tags::find($id);
        return view('backend.tags.edit',compact('tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $request->validate([
            "tags_title" => "required|unique:tags,tags_title,".$id,
            "tags_status" => "required",
        ]);
        try{
            $tags = Tags::find($id);
            $tags->tags_title = $request->input('tags_title');
            $tags->tags_status = $request->input('tags_status');
            $tags->Update();
            request()->session()->flash("successMessage", "Tags Update successfully");


        }
        catch(\Exception $e){
            request()->session()->flash('unsuccessMessage', 'Failed to update Tags');

        }


        return redirect(route('tags.index'));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tags  $tags
     * @return \Illuminate\Http\Response
     */
    public function destroy($tags)
    {
        try{
            // Tags::deleted($tags);
            request()->session()->flash("successMessage", "Tags Delete successfully");
        }
        catch(\Exception $e){
            request()->session()->flash('unsuccessMessage', 'Failed to delete Tags');
        }
        return redirect(route('tags.index'));
    }
}

resources/views/backend/tags/create.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | Add Tags')
@section('content-header')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Tags</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('tags.index') }}">Tags</a></li>
                        <li class="breadcrumb-item active">Add Tags</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <form action="{{ route('tags.store') }}" method="POST" id="news_store" enctype="multipart/form-data" autocomplete="off">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Tags</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="tags_title">Title</label>
                                    <input type="text" class="form-control" name="tags_title" id="tags_title"
                                        placeholder="Title" value="{{ old('tags_title') }}">
                                        @if ($errors->has('tags_title'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('tags_title') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Status</label><br>
                                    <div class="row">
                                        <div class="col-md-12" style="margin-bottom: 5px;">
                                            <input type="radio" name="tags_status" value="1"
                                                {{ !is_null(old('tags_status')) ? (old('tags_status') == 1 ? 'checked' : '') : '' }}>
                                            <span>Active</span>
                                        </div>
                                        <div class="col-md-12">
                                            <input type="radio" name="tags_status" value="0"
                                                {{ !is_null(old('tags_status')) ? (old('tags_status') == 0 ? 'checked' : '') : '' }}>
                                            <span>Inactive</span><br>
                                        </div>
                                    </div>
                                    @if ($errors->has('tags_status'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('tags_status') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="col-12" style="margin-bottom: 10px;">
                           <input type="submit" value="Submit" class="btn btn-sm btn-primary float-right">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/tags/edit.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | Edit news')
@section('content-header')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit News</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('tags.index') }}">News</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <form class="form-horizontal" method="post" action="{{ route('tags.update',$tags->id)}}"
        id="news_edit" enctype="multipart/form-data" autocomplete="off">
        @csrf
        @method('patch')
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Tags</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-10">
                                <div class="form-group">
                                    <label for="tags_title">Title</label>
                                    <input type="text" class="form-control" name="tags_title" id="tags_title"
                                        placeholder="Title" value="{{ !empty($tags) ? $tags->tags_title : '' }}">
                                        @if ($errors->has('tags_title'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('tags_title') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Status</label><br>
                                    <div class="row">
                                        <div class="col-md-12" style="margin-bottom: 5px;">
                                            <input type="radio" name="tags_status" value="1"
                                    <input type="radio" name="status" value="1" {{ !is_null($tags) ? (($tags->tags_status==1)? 'checked' : '') : '' }}>
                                            <span>Active</span>
                                        </div>
                                        <div class="col-md-12">
                                            <input type="radio" name="tags_status" value="0"
                                            {{ !is_null($tags) ? (($tags->tags_status==0)? 'checked' : '') : '' }}>
                                            <span>Inactive</span><br>
                                        </div>
                                    </div>
                                    @if ($errors->has('tags_status'))
                                        <span class="help-block" style="color: #f86c6b;">
                                            {{ $errors->first('tags_status') }}
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="col-12" style="margin-bottom: 10px;">
                            <input type="submit" value="Update" class="btn btn-sm btn-primary float-right">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection
@section('after-script')
@endsection

resources/views/backend/tags/index.blade.php
@extends('backend.layouts.master')
@section('title', env('APP_NAME') . ' | List News')
@section('content-header')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            Tags
                        </li>
                        <li class="breadcrumb-item active">
                            List
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title"><strong>List Tags</strong></h3>
                    <div class="card-tools" style="display: flex;">
                        <div style="margin-right: 10px;">
                            <a href="{{ route('tags.create') }}" class="btn btn-success btn-xs" title="Add Tags">Add
                                Tags</a>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="card-body table-responsive no-padding">
                    <div my-2>
                        @if (session('successMessage'))
                            <div class="alert alert-success"  id="message_id" role="alert">
                                {{ session('successMessage') }}
                            </div>
                            @elseif (session('unsuccessMessage'))
                            <div class="alert alert-danger"  id="message_id" role="alert">
                                {{ session('unsuccessMessage') }}
                            </div>
                        @endif
                    </div>
                    <table class="table table-hover" id="myTable">

                        <thead>

                            <tr>
                                <th width="5%">S.N</th>

                                <th width="33%">Title</th>

                                <th width="8%">Status</th>

                                <th width="15%">Action</th>

                            </tr>

                        </thead>

                    </table>

                </div>

            </div>

            <!-- /.box -->

        </div>

    </div>

@endsection
@section('after-script')

<script type="text/javascript">
    $(function () {

      var table = $('#myTable').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('tags.index') }}",
          columns: [
              {data: 'id', name: 'id'},
              {data: 'tags_title', name: 'tags_title'},
              {data: 'tags_status', name: 'tags_status'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });
      $("body").on('click', '.delete', function (e){
        e.preventDefault();
        var deleteId = $(this).data("id");
        var url = '{{ url('/') }}';
        swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this Tags!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((willDelete) => {
          if (willDelete) {
            $.ajax({
              type: "delete",
              url: url +'/tags/'+ deleteId,
              data: data,
              success: function (response){
                swal(response.status, {
                  icon: "success",
                }).then((result) => {
                  location.reload();
                });
              },
            });
          } else {
            swal("Your Tags is safe!");
          }
        });
      });

    });
  </script>
@endsection